# Generated by Django 4.2.13 on 2024-05-22 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('disposisi_pimpinan', models.BooleanField(default=False)),
                ('approval_kepala_biro', models.BooleanField(default=False)),
                ('kwitansi_filled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_surat_pengajuan', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kwitansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengisian', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('surat_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengajuan.suratpengajuan')),
            ],
        ),
        migrations.CreateModel(
            name='DisposisiPimpinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposisi_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tanggal_disposisi', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('surat_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengajuan.suratpengajuan')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalKepalaBiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tanggal_approval', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('surat_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengajuan.suratpengajuan')),
            ],
        ),
    ]
