# Generated by Django 4.2.13 on 2024-06-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0002_profile'),
        ('pengajuan', '0003_auto_20240602_2025'),
    ]

    operations = [
    ]
