# Generated by Django 4.1.5 on 2024-06-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0005_kwitansi_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratpengajuan',
            name='approval_kepala_biro',
        ),
    ]
